const fs = require('fs')
const path = require('path')

function readFile(fileNo) {
    fs.readFileSync(`file${1}.csv`, { encoding: 'utf8' }) 
}
const startTime = new Date()
console.log('starting file 1 after', new Date() - startTime)
readFile(1)
console.log('starting file 2 after', new Date() - startTime)
readFile(2)
console.log('starting file 3 after', new Date() - startTime)
readFile(3)
console.log('starting file 4 after', new Date() - startTime)
readFile(4)
console.log('starting file 5 after', new Date() - startTime)
readFile(5)
console.log('starting file 6 after', new Date() - startTime)
readFile(6)
console.log('starting file 7 after', new Date() - startTime)
readFile(7)
console.log('starting file 8 after', new Date() - startTime)
readFile(8)
console.log('starting file 9 after', new Date() - startTime)
readFile(9)
console.log('starting file 10 after', new Date() - startTime)
readFile(10)
console.log('starting file 11 after', new Date() - startTime)
readFile(11)
console.log('starting file 12 after', new Date() - startTime)
readFile(12)
console.log('total time: ', new Date() - startTime)
